Welcome to your first set of Python coding problems!

If this is your first time using Kaggle Notebooks, welcome!

Notebooks are composed of blocks (called "cells") of text and code. Each of these is editable, though you'll mainly be editing the code cells to answer some questions.

To get started, try running the code cell below (by pressing the ► button, or clicking on the cell and pressing ctrl+enter on your keyboard).

In [1]:
print("You've successfully run some Python code")
print("Congratulations!")

You've successfully run some Python code
Congratulations!


Experiment in the IPython Shell; print 5 / 8, for example.

Add another line of code to the Python script on the top-right (not in the Shell): print(7 + 10).

In [2]:
# Example, do not modify!
print(5/8)


# Put code below here


0.625


Suppose you have $100, which you can invest with a 10% return each year. After one year, it's 100 x 1.1 = 110 dollars, and after two years it's 100 x 1.1 x 1.1. Add code to calculate how much money you end up with after 7 years, and print the result.

In [3]:
totalYear = 7
ret = 1.1
money = 100

totalMoney = money * (1.1 ** totalYear)
print(totalMoney)


194.87171000000012


Complete the code below. In case it's helpful, here is the table of available arithmetic operations:



| Operator     | Name           | Description                                            |
|--------------|----------------|--------------------------------------------------------|
| ``a + b``    | Addition       | Sum of ``a`` and ``b``                                 |
| ``a - b``    | Subtraction    | Difference of ``a`` and ``b``                          |
| ``a * b``    | Multiplication | Product of ``a`` and ``b``                             |
| ``a / b``    | True division  | Quotient of ``a`` and ``b``                            |
| ``a // b``   | Floor division | Quotient of ``a`` and ``b``, removing fractional parts |
| ``a % b``    | Modulus        | Integer remainder after division of ``a`` by ``b``     |
| ``a ** b``   | Exponentiation | ``a`` raised to the power of ``b``                     |
| ``-a``       | Negation       | The negative of ``a``                                  |


In [4]:
pi = 3.14159 # approximate
diameter = 3

# Create a variable called 'radius' equal to half the diameter
radius=diameter/2;

# Create a variable called 'area', using the formula for the area of a circle: pi times the radius squared
area=pi*radius**2

# Check your answer
print(area)

7.0685775


Create a variable savings with the value 100.

Check out this variable by typing print(savings) in the script

Create a variable growth_multiplier, equal to 1.1.

Create a variable, result, equal to the amount of money you saved after 7 years.

Print out the value of result

In [5]:
# Create a variable savings
saving = 100


# Create a variable growth_multiplier
growth_multiplier = 1.1

# Calculate result
result = saving * (growth_multiplier ** 7)

# Print out result
print(result)

194.87171000000012


Calculate the product of savings and growth_multiplier. Store the result in year 1.

What do you think the resulting type will be? Find out by printing out the type of year 1.

Calculate the sum of desc and desc and store the result in a new variable doubledesc.

Print out doubledesc. Did you expect this?

In [6]:
savings = 100
growth_multiplier = 1.1
desc = "compound interest"

# Assign product of growth_multiplier and savings to year1
year1 = growth_multiplier * savings

# Print the type of year1
print(type(year1))

# Assign sum of desc and desc to doubledesc
doubledesc = desc + desc

# Print out doubledesc
print(doubledesc)


<class 'float'>
compound interestcompound interest



**Create a list**

As opposed to int, bool etc., a list is a compound data type; you can group values together:

a = "is"

b = "nice"

my_list = ["my", "list", a, b]

After measuring the height of your family, you decide to collect some information on the house you're living in. The areas of the different parts of your house are stored in separate variables for now, as shown in the script.

Create a list, areas, that contains the area of the hallway (hall), kitchen (kit), living room (liv), bedroom (bed) and bathroom (bath), in this order. Use the predefined variables.

Print areas with the print() function.

In [7]:
# area variables (in square meters)
hall = 2
kit = 4
liv = 6
bed = 8
bath = 10 

# Create list areas
areas =[hall, kit, liv, bed, bath]


# Print areas
print(areas)

[2, 4, 6, 8, 10]


Finish the code that creates the areas list. Build the list so that the list first contains the name of each room as a string and then its area. In other words, add the strings "hallway", "kitchen" and "bedroom" at the appropriate locations.

Print areas again; is the printout more informative this time?

In [8]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas
areas = ["hallway", hall, "kitchen", kit, "living room", liv,"bedroom", bed, "bathroom", bath]

# Print areas
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


**Execise**

Finish the list of lists so that it also contains the bedroom and bathroom data. Make sure you enter these in order!

Print out house; does this way of structuring your data make more sense?

Print out the type of house. Are you still dealing with a list?

In [9]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath]]

# Print out house
print(house)

# Print out the type of house
print(type(house))

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>


**Subset and conquer**

Subsetting Python lists is a piece of cake. Take the code sample below, which creates a list x and then selects "b" from it. Remember that this is the second element, so it has index 1. You can also use negative indexing.

```
x = ["a", "b", "c", "d"]
x[1]
x[-3] # same result!
```


Remember the areas list from before, containing both strings and floats? Its definition is already in the script. Can you add the correct code to do some Python subsetting?

**Instructions**

Print out the second element from the areas list (it has the value 11.25).

Subset and print out the last element of areas, being 9.50. Using a negative index makes sense here!

Select the number representing the area of the living room (20.0) and print it out.

In [10]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])

# Print out the area of the living room
print(areas[5])

11.25
9.5
20.0


**Subset and calculate**

After you've extracted values from a list, you can use them to perform additional calculations. Take this example, where the second and fourth element of a list x are extracted. The strings that result are pasted together using the + operator:


```
x = ["a", "b", "c", "d"]
print(x[1] + x[3])
```
**Instruction**

Using a combination of list subsetting and variable assignment, create a new variable, eat_sleep_area, that contains the sum of the area of the kitchen and the area of the bedroom.

Print the new variable eat_sleep_area.


In [11]:
# Create the areas list
areas = [["hallway", 11.25], ["kitchen", 18.0], ["living room", 20.0], ["bedroom", 10.75], ["bathroom", 9.50]]

# Sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area = areas[1][1] + areas[3][1]

# Print the variable eat_sleep_area
print(eat_sleep_area)

28.75


#**Slicing and dicing**

Selecting single values from a list is just one part of the story. It's also possible to slice your list, which means selecting multiple elements from your list. Use the following syntax:

`my_list[start:end]`

The start index will be included, while the end index is not.

The code sample below shows an example. A list with "b" and "c", corresponding to indexes 1 and 2, are selected from a list x:

```
x = ["a", "b", "c", "d"]
x[1:3]

```

The elements with index 1 and 2 are included, while the element with index 3 is not.

#**Instructions**
Use slicing to create a list, downstairs, that contains the first 6 elements of areas.

Do a similar thing to create a new variable, upstairs, that contains the last 4 elements of areas.

Print both downstairs and upstairs using print().

In [12]:
# Create the areas list
# areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]
areas = [["hallway", 11.25], ["kitchen", 18.0], ["living room", 20.0], ["bedroom", 10.75], ["bathroom", 9.50]]

# Use slicing to create downstairs
downstairs = areas[0:3]

# Use slicing to create upstairs
upstairs = areas[4:5]

# Print out downstairs and upstairs
print(downstairs)
print(upstairs)

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0]]
[['bathroom', 9.5]]


#**Slicing and dicing (2)**

In the video, Hugo first discussed the syntax where you specify both where to begin and end the slice of your list:

`my_list[begin:end]`

However, it's also possible not to specify these indexes. If you don't specify the begin index, Python figures out that you want to start your slice at the beginning of your list. If you don't specify the end index, the slice will go all the way to the last element of your list. To experiment with this, try the following commands in the IPython Shell:

```
x = ["a", "b", "c", "d"]
x[:2]
x[2:]
x[:]
```

#**Instructions**

Create downstairs again, as the first 6 elements of areas. This time, simplify the slicing by omitting the begin index.

Create upstairs again, as the last 4 elements of areas. This time, simplify the slicing by omitting the end index.

In [13]:
# Create the areas list
# areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]
areas = [["hallway", 11.25], ["kitchen", 18.0], ["living room", 20.0], ["bedroom", 10.75], ["bathroom", 9.50]]

# Alternative slicing to create downstairs
downstairs= areas[:3]

# Alternative slicing to create upstairs
upstairs= areas[4:]

# Print out downstairs and upstairs
print(downstairs)
print(upstairs)

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0]]
[['bathroom', 9.5]]


**Replace list elements**

Replacing list elements is pretty easy. Simply subset the list and assign new values to the subset. You can select single elements or you can change entire list slices at once.

Use the IPython Shell to experiment with the commands below. Can you tell what's happening and why?

```
x = ["a", "b", "c", "d"]
x[1] = "r"
x[2:] = ["s", "t"]
```

For this and the following exercises, you'll continue working on the areas list that contains the names and areas of different rooms in a house.

**Extend a list**

If you can change elements in a list, you sure want to be able to add elements to it, right? You can use the + operator:

```
x = ["a", "b", "c", "d"]
y = x + ["e", "f"]

```

You just won the lottery, awesome! You decide to build a poolhouse and a garage. Can you add the information to the areas list?


**Instructions**
Use the + operator to paste the list ["poolhouse", 24.5] to the end of the areas list. Store the resulting list as areas_1.

Further extend areas_1 by adding data on your garage. Add the string "garage" and float 15.45. Name the resulting list areas_2.

In [14]:
# Create the areas list and make some changes
areas = [["hallway", 11.25], ["kitchen", 18.0], ["chill zone", 20.0],
         ["bedroom", 10.75], ["bathroom", 10.50]]

# Add poolhouse data to areas, new list is areas_1
areas +=  [["poolhouse", 10.00]]

# Add garage data to areas_1, new list is areas_2
areas += [["garage", 11.00]]

print(areas)


[['hallway', 11.25], ['kitchen', 18.0], ['chill zone', 20.0], ['bedroom', 10.75], ['bathroom', 10.5], ['poolhouse', 10.0], ['garage', 11.0]]


#Delete list elements

Finally, you can also remove elements from your list. You can do this with the del statement:

x = ["a", "b", "c", "d"]
del(x[1])
Pay attention here: as soon as you remove an element from a list, the indexes of the elements that come after the deleted element all change!

The updated and extended version of areas that you've built in the previous exercises is coded below. You can copy and paste this into the IPython Shell to play around with the result.

```
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]
```


There was a mistake! The amount you won with the lottery is not that big after all and it looks like the poolhouse isn't going to happen. You decide to remove the corresponding string and float from the areas list.

The ; sign is used to place commands on the same line. The following two code chunks are equivalent:

# Same line
command1; command2

# Separate lines
command1
command2
Which of the code chunks will do the job for us?

#Familiar functions

Out of the box, Python offers a bunch of built-in functions to make your life as a data scientist easier. You already know two such functions: print() and type(). You've also used the functions str(), int(), bool() and float() to switch between data types. These are built-in functions as well.

Calling a function is easy. To get the type of 3.0 and store the output as a new variable, result, you can use the following:

`result = type(3.0)`

The general recipe for calling functions and saving the result to a variable is thus:

`output = function_name(input)`

#Instructions
Use print() in combination with type() to print out the type of var1.

Use len() to get the length of the list var1. Wrap it in a print() call to directly print it out.

Use int() to convert var2 to an integer. Store the output as out2.


In [15]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# Print out type of var1
print(type(var1))

# Print out length of var1
print(type(var2))

# Convert var2 to an integer: out2
out2 = int(var2)
print(out2)
print(type(out2))


<class 'list'>
<class 'bool'>
1
<class 'int'>


#Multiple arguments
In the previous exercise, the square brackets around imag in the documentation showed us that the imag argument is optional. But Python also uses a different way to tell users about arguments being optional.

Have a look at the documentation of sorted() by typing help(sorted) in the IPython Shell.

You'll see that sorted() takes three arguments: iterable, key and reverse.

key=None means that if you don't specify the key argument, it will be None. reverse=False means that if you don't specify the reverse argument, it will be False.

In this exercise, you'll only have to specify iterable and reverse, not key. The first input you pass to sorted() will be matched to the iterable argument, but what about the second input? To tell Python you want to specify reverse without changing anything about key, you can use =:

`sorted(___, reverse = ___)`

Two lists have been created for you in the editor. Can you paste them together and sort them in descending order?

Note: For now, we can understand an iterable as being any collection of objects, e.g. a List.

#Instructions
Use + to merge the contents of first and second into a new list: full.

Call sorted() on full and specify the reverse argument to be True. Save the sorted list as full_sorted.

Finish off by printing out full_sorted.


In [16]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [17]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second

# Sort full in descending order: full_sorted
full_sorted = sorted(full, reverse=True)

# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


#List Methods
Strings are not the only Python types that have methods associated with them. Lists, floats, integers and booleans are also types that come packaged with a bunch of useful methods. In this exercise, you'll be experimenting with:

1.   index(), to get the index of the first element of a list that matches its input, and
2.   count(), to get the number of times an element appears in a list.

You'll be working on the list with the area of different parts of a house: areas.



---


#Instructions
Use the index() method to get the index of the element in areas that is equal to 20.0. Print out this index.

Call count() on areas to find out how many times 9.50 appears in the list. Again, simply print out this number.






In [18]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 9.50 appears in areas
print(areas.count(9.50))

2
1


#**List Methods (2)**

Most list methods will change the list they're called on. Examples are:

* append(), that adds an element to the list it is called on,
* remove(), that removes the first element of a list that matches the input, and
* reverse(), that reverses the order of the elements in the list it is called on.

You'll be working on the list with the area of different parts of the house: areas.

#Instructions
* Use append() twice to add the size of the poolhouse and the garage again: 24.5 and 15.45, respectively. Make sure to add them in this order.
* Print out areas
* Use the reverse() method to reverse the order of the elements in areas.
* Print out areas once more.

In [19]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(1.0)
areas.append(40.0)

# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 1.0, 40.0]
[40.0, 1.0, 9.5, 10.75, 20.0, 18.0, 11.25]


# Import package
As a data scientist, some notions of geometry never hurt. Let's refresh some of the basics.

For a fancy clustering algorithm, you want to find the circumference, , and area, , of a circle. 

To use the constant pi, you'll need the math package. A variable r is already coded in the script. Fill in the code to calculate C and A and see how the print() functions create some nice printouts.

#Instructions
* Import the math package. Now you can access the constant pi with math.pi.
* Calculate the circumference of the circle and store it in C.
* Calculate the area of the circle and store it in A.

In [20]:
# Definition of radius
r = 0.43

# Import the math package
import math
# Calculate C
C = 2 * math.pi * r

# Calculate A
A = math.pi * r**2

# Build printout
print(C, ' ', A)

2.701769682087222   0.5808804816487527


# Selective import
General imports, like import math, make all functionality from the math package available to you. However, if you decide to only use a specific part of a package, you can always make your import more selective:

`from math import pi`

Let's say the Moon's orbit around planet Earth is a perfect circle, with a radius r (in km) that is defined in the script.

# Instructions

* Perform a selective import from the math package where you only import the radians function.
* Calculate the distance travelled by the Moon over 12 degrees of its orbit. Assign the result to dist. You can calculate this as r * phi, where r is the radius and phi is the angle in radians. To convert an angle in degrees to an angle in radians, use the radians() function, which you just imported.
* Print out dist.


In [21]:
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians 

# Travel distance of Moon over 12 degrees. Store in dist.
dist = math.radians(r)

# Print out dist
print(dist)

3359.7588100890844
